version: '3.8'

services:
  chatbot:
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=${DEBUG}
    env_file:
      - .env