# Docker Compose

services:
  chatbot:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=${DEBUG:-False}
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/app/static
    restart: unless-stopped